DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE IF NOT EXISTS PRODUCTS (
  ID int NOT NULL auto_increment,
  CODE varchar(9) NOT NULL,
  DESCRIPTION varchar(15) NOT NULL,
  CREATION_DATE timestamp NOT NULL,
  PRIMARY KEY (CODE)
);